# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

DEBUG ?= 0
MBED_OS_DIR := mbed-dev
FAT_FILESYSTEM_DIR := FATFileSystem
SD_FILESYSTEM_DIR := SDFileSystem

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := ft33


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += main.o
OBJECTS += $(FAT_FILESYSTEM_DIR)/FATDirHandle.o
OBJECTS += $(FAT_FILESYSTEM_DIR)/FATFileHandle.o
OBJECTS += $(FAT_FILESYSTEM_DIR)/FATFileSystem.o
OBJECTS += $(FAT_FILESYSTEM_DIR)/ChaN/ccsbcs.o
OBJECTS += $(FAT_FILESYSTEM_DIR)/ChaN/diskio.o
OBJECTS += $(FAT_FILESYSTEM_DIR)/ChaN/ff.o
OBJECTS += $(SD_FILESYSTEM_DIR)/SDFileSystem.o
OBJECTS += $(MBED_OS_DIR)/drivers/AnalogIn.o
OBJECTS += $(MBED_OS_DIR)/drivers/BusIn.o
OBJECTS += $(MBED_OS_DIR)/drivers/BusInOut.o
OBJECTS += $(MBED_OS_DIR)/drivers/BusOut.o
OBJECTS += $(MBED_OS_DIR)/drivers/CAN.o
OBJECTS += $(MBED_OS_DIR)/drivers/Ethernet.o
OBJECTS += $(MBED_OS_DIR)/drivers/FlashIAP.o
OBJECTS += $(MBED_OS_DIR)/drivers/I2C.o
OBJECTS += $(MBED_OS_DIR)/drivers/I2CSlave.o
OBJECTS += $(MBED_OS_DIR)/drivers/InterruptIn.o
OBJECTS += $(MBED_OS_DIR)/drivers/InterruptManager.o
OBJECTS += $(MBED_OS_DIR)/drivers/RawSerial.o
OBJECTS += $(MBED_OS_DIR)/drivers/SPI.o
OBJECTS += $(MBED_OS_DIR)/drivers/SPISlave.o
OBJECTS += $(MBED_OS_DIR)/drivers/Serial.o
OBJECTS += $(MBED_OS_DIR)/drivers/SerialBase.o
OBJECTS += $(MBED_OS_DIR)/drivers/Ticker.o
OBJECTS += $(MBED_OS_DIR)/drivers/Timeout.o
OBJECTS += $(MBED_OS_DIR)/drivers/Timer.o
OBJECTS += $(MBED_OS_DIR)/drivers/TimerEvent.o
OBJECTS += $(MBED_OS_DIR)/drivers/UARTSerial.o
OBJECTS += $(MBED_OS_DIR)/hal/mbed_flash_api.o
OBJECTS += $(MBED_OS_DIR)/hal/mbed_gpio.o
OBJECTS += $(MBED_OS_DIR)/hal/mbed_lp_ticker_api.o
OBJECTS += $(MBED_OS_DIR)/hal/mbed_pinmap_common.o
OBJECTS += $(MBED_OS_DIR)/hal/mbed_ticker_api.o
OBJECTS += $(MBED_OS_DIR)/hal/mbed_us_ticker_api.o
OBJECTS += $(MBED_OS_DIR)/platform/ATCmdParser.o
OBJECTS += $(MBED_OS_DIR)/platform/CallChain.o
OBJECTS += $(MBED_OS_DIR)/platform/FileBase.o
OBJECTS += $(MBED_OS_DIR)/platform/FileHandle.o
OBJECTS += $(MBED_OS_DIR)/platform/FilePath.o
OBJECTS += $(MBED_OS_DIR)/platform/FileSystemHandle.o
OBJECTS += $(MBED_OS_DIR)/platform/LocalFileSystem.o
OBJECTS += $(MBED_OS_DIR)/platform/Stream.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_alloc_wrappers.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_application.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_assert.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_board.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_critical.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_error.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_interface.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_mem_trace.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_mktime.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_poll.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_retarget.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_rtc_time.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_sdk_boot.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_semihost_api.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_stats.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_wait_api_no_rtos.o
OBJECTS += $(MBED_OS_DIR)/platform/mbed_wait_api_rtos.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_LPC11U37H_401/PeripheralPins.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/analogin_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/startup_LPC11xx.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/device/cmsis_nvic.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/device/system_LPC11Uxx.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/gpio_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/gpio_irq_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/i2c_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/pinmap.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/port_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/pwmout_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/serial_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/sleep.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/spi_api.o
OBJECTS += $(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/us_ticker.o


INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../img
INCLUDE_PATHS += -I../$(FAT_FILESYSTEM_DIR)
INCLUDE_PATHS += -I../$(FAT_FILESYSTEM_DIR)/ChaN
INCLUDE_PATHS += -I../$(SD_FILESYSTEM_DIR)
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/.
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/cmsis
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/cmsis/TARGET_CORTEX_M
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/cmsis/TARGET_CORTEX_M/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/cmsis/TOOLCHAIN_GCC
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/drivers
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/hal
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/hal/storage_abstraction
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/platform
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets/TARGET_NXP
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_LPC11U37H_401
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/device
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../$(MBED_OS_DIR)/targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U37H_401

LIBRARY_PATHS :=
LIBRARIES :=
LINKER_SCRIPT ?= ../LPC11U37.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-DMBED_RTOS_SINGLE_THREAD' '-mcpu=cortex-m0' '-mthumb'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-DMBED_RTOS_SINGLE_THREAD' '-mcpu=cortex-m0' '-mthumb'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-DMBED_RTOS_SINGLE_THREAD' '-mcpu=cortex-m0' '-mthumb'
LD      = 'arm-none-eabi-gcc'
ELF2BIN = 'arm-none-eabi-objcopy'
PREPROC = 'arm-none-eabi-cpp' '-E' '-P' '-Wl,--gc-sections' '-Wl,--wrap,main' '-Wl,--wrap,_malloc_r' '-Wl,--wrap,_free_r' '-Wl,--wrap,_realloc_r' '-Wl,--wrap,_memalign_r' '-Wl,--wrap,_calloc_r' '-Wl,--wrap,exit' '-Wl,--wrap,atexit' '-Wl,-n' '--specs=nano.specs' '-mcpu=cortex-m0' '-mthumb'


ifeq ($(DEBUG), 1)
# Do not optimize so the source matches the object code and add in the maximum debug information
C_FLAGS += '-O0' '-g3'
else
C_FLAGS += '-Os' '-DNDEBUG'
endif

C_FLAGS += -std=gnu99
C_FLAGS += -DDEVICE_ERROR_PATTERN=1
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DTARGET_NXP
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTARGET_LPC11UXX
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DARM_MATH_CM0
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_M0
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTARGET_LPCTarget
C_FLAGS += -D__CORTEX_M0
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1506341399.67
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DDEVICE_SEMIHOST=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M0
C_FLAGS += -DDEVICE_LOCALFILESYSTEM=1
C_FLAGS += -DOPEN_MAX=4
C_FLAGS += -include
C_FLAGS += mbed_config.h

ifeq ($(DEBUG), 1)
# Do not optimize so the source matches the object code and add in the maximum debug information
CXX_FLAGS += '-O0' '-g3'
else
CXX_FLAGS += '-Os' '-DNDEBUG'
endif

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DDEVICE_ERROR_PATTERN=1
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DTARGET_NXP
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTARGET_LPC11UXX
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DARM_MATH_CM0
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_M0
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTARGET_LPCTarget
CXX_FLAGS += -D__CORTEX_M0
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1506341399.67
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DDEVICE_SEMIHOST=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M0
CXX_FLAGS += -DDEVICE_LOCALFILESYSTEM=1
CXX_FLAGS += -DOPEN_MAX=4
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ifeq ($(DEBUG), 1)
# Do not optimize so the source matches the object code and add in the maximum debug information
ASM_FLAGS += '-O0' '-g3'
else
ASM_FLAGS += '-Os' '-DNDEBUG'
endif

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -D__CORTEX_M0
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL
ASM_FLAGS += -DCMSIS_VECTAB_VIRTUAL_HEADER_FILE=\"cmsis_nvic.h\"
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DARM_MATH_CM0
ASM_FLAGS += -D__CMSIS_RTOS


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n --specs=nano.specs -mcpu=cortex-m0 -mthumb -Wl,-Map=ft33.map -Wl,--cref
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.asm.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter %.ld, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
